name: Publication to Chrome Webstore

on:
  release:
    types: ['released']

jobs:
  chrome-webstore-publication:
    runs-on: ubuntu-latest
    environment:
      name: Chrome Webstore
      url: https://chromewebstore.google.com/detail/homedash-enhanced-new-tab/ndnbhanjlibkgnalfbojjmjlpnnedojf
    steps:
      - uses: actions/checkout@v4

      - name: Prepare workflow
        uses: ./.github/actions/prepare-workflow

      - name: Building extension
        run: pnpm build

      - name: Install zip utility
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Archive dist
        run: mkdir -p /tmp/${{ github.repository }}/${{ github.sha }} && zip -r /tmp/${{ github.repository }}/${{ github.sha }}/home-dash.zip dist

      - name: Get dist size
        run: du -h /tmp/${{ github.repository }}/${{ github.sha }}/home-dash.zip

      - name: Publish to Chrome Store
        uses: wdzeng/chrome-extension@v1
        with:
          extension-id: ndnbhanjlibkgnalfbojjmjlpnnedojf
          zip-path: /tmp/${{ github.repository }}/${{ github.sha }}/home-dash.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
